version: "3.1"
services:

    php:
#      container_name: app-php
      image: grambas/php73-xdebug:1.0
      expose:
        - 9001
#       environment:
#         PHP_XDEBUG_ENABLED: 1
#         XDEBUG_CONFIG: remote_host=172.17.0.1
      volumes:
        - ./app:/srv/webcontent
        - ./docker/php/crons:/etc/cron.d/
        - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      restart: on-failure
      links:
        - mysql
        
    mysql:
      image: mysql:8.0
#      container_name: app-mysql
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: app
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: app
      command:
        - "--default-authentication-plugin=mysql_native_password"
#      ports:
#        - 3000:3306
      volumes:
        - app-mysql-volume:/var/lib/mysql
        # - ./logs/mysql:/var/log/mysql

    nginx:
      image: nginx:1.15.3-alpine
#      container_name: app-nginx
      restart: on-failure
      expose:
        - 80 
      volumes:
        - ./app:/srv/webcontent
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./logs/nginx:/var/log/nginx:cached
      environment:
        VIRTUAL_HOST: app-stage.vytis.space
#        LETSENCRYPT_HOST: app-stage.vytis.space
#        LETSENCRYPT_EMAIL: logs@mindau.de
#       ports:
#          - 8003:80
      depends_on:
        - php

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  app-mysql-volume:
